LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := app
LOCAL_LDFLAGS := -Wl,--build-id
LOCAL_SRC_FILES := \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs/arm64-v8a/libopencv_java3.so \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs/armeabi/libopencv_java3.so \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs/armeabi-v7a/libopencv_java3.so \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs/mips/libopencv_java3.so \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs/mips64/libopencv_java3.so \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs/x86/libopencv_java3.so \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs/x86_64/libopencv_java3.so \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-arm64-v8a/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-arm64-v8a/OpenCVConfig.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-arm64-v8a/OpenCVModules-release.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-arm64-v8a/OpenCVModules.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi/OpenCVConfig.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi/OpenCVModules-release.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi/OpenCVModules.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi-v7a/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi-v7a/OpenCVConfig.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi-v7a/OpenCVModules-release.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-armeabi-v7a/OpenCVModules.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips/OpenCVConfig.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips/OpenCVModules-release.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips/OpenCVModules.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips64/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips64/OpenCVConfig.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips64/OpenCVModules-release.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-mips64/OpenCVModules.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86/OpenCVConfig.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86/OpenCVModules-release.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86/OpenCVModules.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86_64/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86_64/OpenCVConfig.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86_64/OpenCVModules-release.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/abi-x86_64/OpenCVModules.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/android.toolchain.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv/cv.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv/cvaux.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv/cxcore.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv/cxeigen.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/calib3d/calib3d.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/calib3d.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/affine.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/base.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/bufferpool.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/core.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/block.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/border_interpolate.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/color.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/common.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/datamov_utils.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/detail/color_detail.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/detail/reduce.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/detail/reduce_key_val.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/detail/transform_detail.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/detail/type_traits_detail.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/detail/vec_distance_detail.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/dynamic_smem.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/emulation.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/filters.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/funcattrib.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/functional.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/limits.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/reduce.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/saturate_cast.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/scan.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/simd_functions.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/transform.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/type_traits.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/utility.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/vec_distance.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/vec_math.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/vec_traits.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/warp.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/warp_reduce.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda/warp_shuffle.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda.inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda_stream_accessor.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cuda_types.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cvstd.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/cvstd.inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/directx.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/eigen.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/fast_math.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/hal/hal.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/hal/intrin.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/hal/intrin_cpp.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/hal/intrin_neon.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/hal/intrin_sse.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/hal/intrin_vsx.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/ippasync.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/mat.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/mat.inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/matx.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/neon_utils.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/ocl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/ocl_genbase.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/ocl_defs.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/opencl_info.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/opencl_svm.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_clamdblas.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_clamdfft.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_core_wrappers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/autogenerated/opencl_gl_wrappers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_clamdblas.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_clamdfft.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_core.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_gl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_gl_wrappers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_svm_20.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_svm_definitions.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opencl/runtime/opencl_svm_hsa_extension.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/opengl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/operations.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/optim.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/ovx.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/persistence.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/ptr.inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/saturate.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/softfloat.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/sse_utils.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/traits.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/types.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/utility.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/utils/filesystem.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/utils/logger.defines.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/utils/logger.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/utils/trace.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/va_intel.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/version.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/vsx_utils.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core/wimage.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/core.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn/all_layers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn/dict.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn/dnn.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn/dnn.inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn/layer.details.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn/layer.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn/shape_utils.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/dnn.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/features2d/features2d.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/features2d.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/flann/flann.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/flann/flann_base.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/flann/miniflann.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/flann.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/highgui/highgui.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/highgui.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/imgcodecs/imgcodecs.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/imgcodecs.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/imgproc/detail/distortion_model.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/imgproc/hal/hal.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/imgproc/imgproc.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/imgproc.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/ml/ml.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/ml/ml.inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/ml.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/objdetect/detection_based_tracker.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/objdetect/objdetect.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/objdetect.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/opencv.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/opencv_modules.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/photo/cuda.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/photo/photo.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/photo.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/shape/emdL1.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/shape/hist_cost.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/shape/shape.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/shape/shape_distance.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/shape/shape_transformer.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/shape.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/autocalib.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/blenders.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/camera.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/exposure_compensate.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/matchers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/motion_estimators.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/seam_finders.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/timelapsers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/util.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/util_inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/warpers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/detail/warpers_inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching/warpers.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/stitching.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/superres/optical_flow.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/superres.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/video/background_segm.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/video/tracking.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/video/video.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/video.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videoio/videoio.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videoio.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/deblurring.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/fast_marching.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/fast_marching_inl.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/frame_source.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/global_motion.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/inpainting.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/log.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/motion_core.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/motion_stabilizing.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/optical_flow.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/outlier_rejection.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/ring_buffer.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/stabilizer.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab/wobble_suppression.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/include/opencv2/videostab.hpp \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV-arm64-v8a.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV-armeabi-v7a.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV-armeabi.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV-mips.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV-mips64.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV-x86.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV-x86_64.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCV.mk \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCVConfig-version.cmake \
	/Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni/OpenCVConfig.cmake \

LOCAL_C_INCLUDES += /Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/debug/jni
LOCAL_C_INCLUDES += /Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jniLibs
LOCAL_C_INCLUDES += /Users/yangjiang/Documents/workspace/android/android-sudoku/app/src/main/jni

include $(BUILD_SHARED_LIBRARY)
